name: snailicide/build
on:
    workflow_call:
        inputs:
            ARCHIVE_PATH:
                required: true
                type: string
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    testme:
        runs-on: ubuntu-latest
        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
            contents: write
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Setup Node.js environment 🛎️
              uses: actions/setup-node@v3.8.1

            - name: Install pnpm 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: |
                  npm install -g pnpm
                  git branch
                  pnpm install

              if: ${{ github.event.act}}
            - run: |
                  echo "🍏 TRACE SECRET FROM FILE---- ${{ secrets.GITHUB_TOKEN }}"  | sed 's/./& /g'
                  git branch

            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

            - name: Install pnpm 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: |
                  pnpm install  --no-frozen-lockfile

            - name: BUILD ALL PACKAGES
              if: ${{ github.event.act}}
              run: |
                  pnpm run build

            - name: CHECK BUILD STATUS
              run: |
                  git status
                  pnpm changeset version
                  git status
                  pnpm changeset version
                  pnpm changeset tag
                  git status
                  git log --oneline

            - name: AUTOCOMMIT NEW  🛎️
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'style(root): formatted by bot'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
